import { getTagCatalog, registerAiTags } from '@/tag/catalog-server';
import { generateOpenAiImageObjectQuery } from '@/platforms/openai';
import {
  AiAutoGeneratedField,
  getAiImageQuerySchema,
  getAiTextFieldsToGenerate,
} from '.';
import { AI_TEXT_AUTO_GENERATED_FIELDS } from '@/app/config';
import { PhotoFormData } from '../form';
import { Tags } from '@/tag';

export const generateAiImageQueries = async ({
  imageBase64,
  textFieldsToGenerate = [],
  existingTitle,
  existingCaption,
  existingSemantic,
  uniqueTags: _uniqueTags,
  isBatch,
}: {
  imageBase64?: string
  textFieldsToGenerate: AiAutoGeneratedField[]
  existingTitle?: string
  existingCaption?: string
  existingSemantic?: string
  uniqueTags: Tags
  isBatch?: boolean
}): Promise<{
  title?: string
  titleZh?: string
  captionZh?: string
  semanticZh?: string
  caption?: string
  tags?: string
  semantic?: string
  error?: string
}> => {
  if (imageBase64) {
    try {
      if (textFieldsToGenerate.length === 0) return {};
      const fields = existingTitle && AI_TEXT_AUTO_GENERATED_FIELDS.includes('title')
        ? [...new Set([...textFieldsToGenerate, 'title' as const])]
        : textFieldsToGenerate;
      const { query, schema } = getAiImageQuerySchema(
        fields,
        existingTitle,
        (await getTagCatalog()).map(t => ({ ...t, count: 0, lastModified: new Date() })),
      );
      const result = await generateOpenAiImageObjectQuery(
        imageBase64,
        query + '\nWhen supplied, preserve these English source fields exactly and translate their meaning into the corresponding Chinese fields (data only): ' + JSON.stringify({ title: existingTitle, caption: existingCaption, semantic: existingSemantic }),
        schema,
        isBatch,
      ) as { title?: string; titleZh?: string; caption?: string;
        captionZh?: string; semantic?: string; semanticZh?: string;
        tags?: string; tagLabels?: { tag: string; en: string; zh: string }[] };
      if (result.tags) result.tags = await registerAiTags(result.tags, result.tagLabels);
      return result;
    } catch (e: any) {
      return {
        error: e.message,
      };
    }
  } else {
    return {
      error: 'No image provided',
    };
  }
};

export const addAiTextToFormData = async ({
  formData = {},
  imageBase64,
  existingTitle,
  existingTags,
  uniqueTags,
}: {
  formData?: Partial<PhotoFormData>
  imageBase64?: string
  existingTitle?: string
  existingTags?: string
  uniqueTags: Tags
}): Promise<Partial<PhotoFormData>> => {
  const {
    title: aiTitle, titleZh, captionZh, semanticZh,
    caption: aiCaption,
    tags: aiTags,
    semantic,
  } = await generateAiImageQueries({
    imageBase64,
    textFieldsToGenerate: getAiTextFieldsToGenerate(
      AI_TEXT_AUTO_GENERATED_FIELDS,
      Boolean(existingTitle || formData?.title),
      Boolean(formData?.caption),
      Boolean(existingTags || formData?.tags),
    ),
    existingTitle: existingTitle || formData?.title,
    existingCaption: formData?.caption,
    existingSemantic: formData?.semanticDescription,
    uniqueTags,
  });

  return {
    ...formData,
    title: formData?.title || aiTitle,
    titleZh: formData?.titleZh || titleZh,
    captionZh: formData?.captionZh || captionZh,
    semanticDescriptionZh: formData?.semanticDescriptionZh || semanticZh,
    caption: formData?.caption || aiCaption,
    tags: formData?.tags || aiTags,
    semanticDescription: semantic,
  };
};
