import { useCallback, useEffect, useRef, useState } from 'react';
import { generateBilingualMetadataAction } from '../actions';
import { AI_AUTO_GENERATED_FIELDS_ALL, AiAutoGeneratedField } from '.';
import { toastWarning } from '@/toast';

export type AiContent = ReturnType<typeof useAiImageQueries>;
export default function useAiImageQueries(
  imageBase64?: string,
  textFieldsToAutoGenerate: AiAutoGeneratedField[] = [],
) {
  const [content, setContent] = useState<Awaited<ReturnType<
    typeof generateBilingualMetadataAction>>>({});
  const [loading, setLoading] = useState<AiAutoGeneratedField[]>([]);
  const running = useRef(false);
  const hasRun = useRef(false);
  const request = useCallback(async (fields = AI_AUTO_GENERATED_FIELDS_ALL) => {
    if (!imageBase64 || running.current) return;
    running.current = true;
    hasRun.current = true;
    setLoading(fields);
    setContent(current => {
      const next = { ...current };
      for (const field of fields) {
        delete next[field];
        if (field === 'title') delete next.titleZh;
        if (field === 'caption') delete next.captionZh;
        if (field === 'semantic') delete next.semanticZh;
      }
      return next;
    });
    try {
      const result = await generateBilingualMetadataAction(imageBase64, fields);
      setContent(current => ({ ...current, ...result }));
    } catch (error) {
      toastWarning(error instanceof Error ? error.message : 'AI generation failed');
    } finally { running.current = false; setLoading([]); }
  }, [imageBase64]);
  useEffect(() => {
    if (imageBase64 && !hasRun.current && textFieldsToAutoGenerate.length) {
      request(textFieldsToAutoGenerate);
    }
  }, [imageBase64, request, textFieldsToAutoGenerate]);
  return {
    request, ...content,
    semanticDescription: content.semantic,
    semanticDescriptionZh: content.semanticZh,
    isLoading: loading.length > 0,
    isLoadingTitle: loading.includes('title'),
    isLoadingCaption: loading.includes('caption'),
    isLoadingTags: loading.includes('tags'),
    isLoadingSemantic: loading.includes('semantic'),
  };
}
