'use client';
import { useUiText } from '@/i18n/UiText';
import UiText from '@/i18n/UiText';

import {
  ComponentProps,
  Fragment,
  JSX,
  ReactNode,
  useEffect,
  useState,
} from 'react';
import ChecklistRow from '@/components/ChecklistRow';
import ChecklistGroup from '@/components/ChecklistGroup';
import { AppConfiguration } from '@/app/config';
import StatusIcon from '@/components/StatusIcon';
import { labelForStorage } from '@/platforms/storage';
import { testConnectionsAction } from '@/admin/actions';
import ErrorNote from '@/components/ErrorNote';
import SecretGenerator from '@/app/SecretGenerator';
import EnvVar from '@/components/EnvVar';
import AdminLink from '@/admin/AdminLink';
import ScoreCardContainer from '@/components/ScoreCardContainer';
import { CATEGORY_KEYS, DEFAULT_CATEGORY_KEYS } from '@/category';
import {
  AI_AUTO_GENERATED_FIELDS_ALL,
  AI_AUTO_GENERATED_FIELDS_DEFAULT,
} from '@/photo/ai';
import clsx from 'clsx/lite';
import Link from 'next/link';
import {
  PATH_ADMIN_AI_MODELS,
  PATH_FEED_JSON,
  PATH_LIBRARY,
  PATH_RSS_XML,
} from '@/app/path';
import { APP_DEFAULT_SORT_BY, DEFAULT_SORT_BY_OPTIONS } from '@/photo/sort';
import {
  AdminConfigSection,
  ConfigSectionKey,
  getAdminConfigSections,
} from '.';
import ColorDot from '@/photo/color/ColorDot';
import { Oklch } from '@/photo/color/client';
import { getOrderedKeyListStatus } from '@/utility/key';
import { DEFAULT_SOCIAL_KEYS, SOCIAL_KEYS } from '@/social';
import MaskedScroll from '@/components/MaskedScroll';
import { IoLink } from 'react-icons/io5';

export default function AdminAppConfigurationClient({
  // Storage
  hasDatabase,
  isPostgresSslEnabled,
  hasRedisStorage,
  hasStorageProvider,
  hasCloudflareR2Storage,
  hasAwsS3Storage,
  hasMinioStorage,
  hasMultipleStorageProviders,
  currentStorage,
  // Auth
  hasAuthSecret,
  hasAdminUser,
  // Content
  locale,
  hasLocale,
  domain,
  hasDomain,
  metaTitle,
  isMetaTitleConfigured,
  metaDescription,
  isMetaDescriptionConfigured,
  navTitle,
  hasNavTitle,
  navCaption,
  hasNavCaption,
  sidebarText,
  hasSidebarText,
  // Performance
  isStaticallyOptimized,
  arePhotosStaticallyOptimized,
  arePhotoOGImagesStaticallyOptimized,
  arePhotoCategoriesStaticallyOptimized,
  arePhotoCategoryOgImagesStaticallyOptimized,
  areOriginalUploadsPreserved,
  hasImageQuality,
  imageQuality,
  isBlurEnabled,
  // AI
  hasOpenaiSecretKey,
  openaiModel,
  aiContentGenerationProvider,
  isAiContentGenerationEnabled,
  aiTextAutoGeneratedFields,
  hasAiTextAutoGeneratedFields,
  // Location
  isGeoPrivacyEnabled,
  hasLocationServices,
  autoGenerateLocations,
  // Categories
  hasCategoryVisibility,
  categoryVisibility,
  showCategoriesOnMobile,
  showCategoryImageHover,
  collapseSidebarCategories,
  hideTagsWithOnePhoto,
  // Sort
  hasDefaultSortBy,
  defaultSortBy,
  hasNavSortControl,
  navSortControl,
  isColorSortEnabled,
  hasColorSortConfiguration,
  colorSortStartingHue,
  colorSortChromaCutoff,
  isSortWithPriority,
  // Display
  showKeyboardShortcutTooltips,
  showExifInfo,
  alwaysShowExposureComp,
  showZoomControls,
  showTakenAtTimeHidden,
  showRepoLink,
  // Grid
  isGridHomepageEnabled,
  isMasonryGridEnabled,
  gridAspectRatio,
  hasGridAspectRatio,
  hasHighGridDensity,
  hasGridDensityPreference,
  // Design
  hasDefaultTheme,
  defaultTheme,
  arePhotoTitlesUppercase,
  arePhotosMatted,
  arePhotoMatteColorsConfigured,
  matteColor,
  matteColorDark,
  areFoldersTinted,
  // Settings
  arePublicDownloadsEnabled,
  hasSocialKeys,
  socialKeys,
  areSiteFeedsEnabled,
  isOgTextBottomAligned,
  // Scripts & Analytics
  hasPageScriptUrls,
  pageScriptUrls,
  // Debugging
  isDebuggingEnabled,
  // Internal
  areInternalToolsEnabled,
  areAdminDebugToolsEnabled,
  isAdminSqlDebugEnabled,
  isAdminStorageDebugEnabled,
  isAdminAiModelDebugEnabled,
  // Auth
  secret,
  // Connection status
  databaseError,
  storageError,
  redisError,
  aiError,
  locationError,
  // Component props
  simplifiedView,
  isAnalyzingConfiguration,
}: AppConfiguration &
  { secret: string } &
  Partial<Awaited<ReturnType<typeof testConnectionsAction>>> & {
    simplifiedView?: boolean
    isAnalyzingConfiguration?: boolean
  }) {
  const uiText = useUiText();
  const [hasScrolled, setHasScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => { setHasScrolled(true); };
    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  const renderContent = (content?: ReactNode) => content
    ? <div className={clsx(
      'my-1 px-2 py-1',
      'bg-dim rounded-lg',
    )}>
      {content}
    </div>
    : null;

  const renderEnvVars = (variables: (string | {
    variable: string,
    optional?: boolean,
    value?: string,
  })[]) =>
    <div className="pt-1 flex flex-col gap-0.5">
      {variables.map(_variable => {
        const { variable, optional, value } = typeof _variable === 'string'
          ? { variable: _variable }
          : _variable;
        return <EnvVar
          key={variable}
          {...{
            variable,
            value,
            ...optional && { trailingContent:
              <span className="text-dim"> <UiText text="(optional)" /> </span>,
            },
          }}
        />;
      })}
    </div>;

  const renderSubStatus = (
    type: ComponentProps<typeof StatusIcon>['type'],
    label: ReactNode,
    iconClassName = 'translate-y-[4px]',
  ) =>
    <div className="flex gap-2">
      <StatusIcon {...{ type, className: iconClassName }} />
      <span className="min-w-0">
        {label}
      </span>
    </div>;

  const renderSubStatusWithEnvVar = (
    type: ComponentProps<typeof StatusIcon>['type'],
    variable: string,
  ) =>
    renderSubStatus(
      type,
      renderEnvVars([variable]),
      'translate-y-[7px]',
    );

  const renderOrderedKeyList = (
    selectedKeys: string[],
    acceptedKeys: readonly string[],
  ) =>
    <div>
      {getOrderedKeyListStatus({ selectedKeys, acceptedKeys })
        .map(({ label, selected }) =>
          <Fragment key={label}>
            {renderSubStatus(
              selected ? 'checked' : 'optional',
              selected
                ? label
                : <span className="text-dim">{label}</span>,
            )}
          </Fragment>)}
    </div>;

  const renderError = ({
    connection,
    message,
  }: {
    connection?: { provider: string, error: string }
    message?: string
  }) =>
    <ErrorNote className="mt-2 mb-3">
      {connection && <>
        {connection.provider} <UiText text="connection error:" /> {`"${connection.error}"`}
      </>}
      {message}
    </ErrorNote>;

  const renderLink = (
    href: string,
    children?: ReactNode,
    isExternal = true,
  ) =>
    <Link
      href={href}
      className="underline underline-offset-3 hover:no-underline"
      target={isExternal ? '_blank' : undefined}
    >
      {children || href}
    </Link>;

  const renderColorDot = (color: Oklch | string, includeTooltip?: boolean) =>
    <ColorDot
      color={color}
      className="size-3! ml-1"
      includeTooltip={includeTooltip}
    />;

  const renderCommaSeparatedList = (items: string[]) =>
    <>
      {'"'}
      {items.map((item, index) => <Fragment key={index}>
        {item}{index < items.length - 1 ? <>,&#8203;</> : <></>}
      </Fragment>)}
      {'"'}
    </>;

  const renderGroupContent = (key: ConfigSectionKey): JSX.Element => {
    switch (key) {
      case 'Storage':
        return <>
          <ChecklistRow
            title={hasDatabase && isAnalyzingConfiguration
              ? 'Testing database connection'
              : 'Setup database'}
            status={hasDatabase}
            isPending={hasDatabase && isAnalyzingConfiguration}
          >
            {databaseError && renderError({
              connection: { provider: 'Database', error: databaseError},
            })}
            {hasDatabase
              ? renderSubStatus(
                'checked',
                // eslint-disable-next-line max-len
                `Postgres: connected${!isPostgresSslEnabled ? ' (SSL disabled)' : ''}`,
              )
              : renderSubStatus('missing', <> <UiText text="Postgres:" /> {' '}
                <AdminLink
                  href="https://neon.com/docs/import/import-from-postgres"
                  externalIcon
                > <UiText text="create database" /> </AdminLink>
                {' '} <UiText text="and set DATABASE_URL" /> </>)}
          </ChecklistRow>
          <ChecklistRow
            title={
              hasStorageProvider && isAnalyzingConfiguration
                ? 'Testing storage connection'
                : !hasStorageProvider
                  ? 'Setup storage (one of the following)'
                  : hasMultipleStorageProviders
                  // eslint-disable-next-line max-len
                    ? `Setup storage (new uploads go to: ${labelForStorage(currentStorage)})`
                    : 'Setup storage'}
            status={hasStorageProvider}
            isPending={hasStorageProvider && isAnalyzingConfiguration}
          >
            {storageError && renderError({
              connection: { provider: 'Storage', error: storageError},
            })}
            <div>
              {hasCloudflareR2Storage
                ? renderSubStatus('checked', 'Cloudflare R2: connected')
                : renderSubStatus('optional', <>
                  {labelForStorage('cloudflare-r2')}:
                  {' '}
                  <AdminLink
                  // eslint-disable-next-line max-len
                    href="https://github.com/sambecker/exif-photo-blog#cloudflare-r2"
                    externalIcon
                  > <UiText text="create/configure bucket" /> </AdminLink>
                </>)}
              {hasAwsS3Storage
                ? renderSubStatus('checked', 'AWS S3: connected')
                : renderSubStatus('optional', <>
                  {labelForStorage('aws-s3')}:
                  {' '}
                  <AdminLink
                    href="https://github.com/sambecker/exif-photo-blog#aws-s3"
                    externalIcon
                  > <UiText text="create/configure bucket" /> </AdminLink>
                </>)}
              {hasMinioStorage
                ? renderSubStatus('checked', 'MinIO: connected')
                : renderSubStatus('optional', <>
                  {labelForStorage('minio')}:
                  {' '}
                  <AdminLink
                    href="https://github.com/sambecker/exif-photo-blog#minio"
                    externalIcon
                  > <UiText text="setup MinIO server" /> </AdminLink>
                </>)}
            </div>
          </ChecklistRow>
        </>;
      case 'Authentication':
        return <>
          <ChecklistRow
            title={!hasAuthSecret && isAnalyzingConfiguration
              ? 'Generating secret'
              : 'Setup auth'}
            status={hasAuthSecret}
            isPending={!hasAuthSecret && isAnalyzingConfiguration}
          > <UiText text="Store auth secret in environment variable" /> {!hasAuthSecret &&
            <div className="overflow-x-auto">
              <SecretGenerator {...{ secret }} />
            </div>}
            {renderEnvVars(['AUTH_SECRET'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Setup admin user')}
            status={hasAdminUser}
          > <UiText text="Store admin email/password" /> {' '} <UiText text="in environment variables" /> {renderEnvVars([
              'ADMIN_EMAIL',
              'ADMIN_PASSWORD',
            ])}
          </ChecklistRow>
        </>;
      case 'Content':
        return <>
          <ChecklistRow
            title={uiText('Configure language')}
            status={hasLocale}
            optional
          >
            {renderContent(locale)} <UiText text="Check README for" /> {' '}
            <AdminLink
            // eslint-disable-next-line max-len
              href="https://github.com/sambecker/exif-photo-blog?tab=readme-ov-file#supported-languages"
            > <UiText text="supported languages" /> </AdminLink>
            {renderEnvVars(['NEXT_PUBLIC_LOCALE'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Configure domain')}
            status={hasDomain}
          >
            {renderContent(domain)} <UiText text="Used in explicit share urls (seen in nav if no title is defined)" /> {renderEnvVars(['NEXT_PUBLIC_DOMAIN'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Meta title')}
            status={isMetaTitleConfigured}
            showWarning
          >
            {renderContent(metaTitle)} <UiText text="Seen in search results and browser tab" /> {renderEnvVars(['NEXT_PUBLIC_META_TITLE'])}
          </ChecklistRow>
          {!simplifiedView && <>
            <ChecklistRow
              title={uiText('Meta description')}
              status={isMetaDescriptionConfigured}
              optional
            >
              {renderContent(metaDescription)} <UiText text="Seen in search results" /> {renderEnvVars(['NEXT_PUBLIC_META_DESCRIPTION'])}
            </ChecklistRow>
            <ChecklistRow
              title={uiText('Nav title')}
              status={hasNavTitle}
              optional
            >
              {renderContent(navTitle)} <UiText text="Replaces domain in top-right nav" /> {renderEnvVars(['NEXT_PUBLIC_NAV_TITLE'])}
            </ChecklistRow>
            <ChecklistRow
              title={uiText('Nav caption')}
              status={hasNavCaption}
              optional
            >
              {hasNavCaption && renderContent(navCaption)} <UiText text="Seen in top-right nav, under title" /> {renderEnvVars(['NEXT_PUBLIC_NAV_CAPTION'])}
            </ChecklistRow>
            <ChecklistRow
              title={uiText('Sidebar text')}
              status={hasSidebarText}
              optional
            >
              {hasSidebarText && renderContent(sidebarText)} <UiText text="Seen in sidebar on desktop grid view" /> {renderEnvVars(['NEXT_PUBLIC_SIDEBAR_TEXT'])}
            </ChecklistRow>
          </>}
        </>;
      case 'External Services':
        return <>
          <ChecklistRow
            title={hasRedisStorage && isAnalyzingConfiguration
              ? 'Testing Redis connection'
              : 'Rate limiting'}
            status={hasRedisStorage}
            isPending={hasRedisStorage && isAnalyzingConfiguration}
            showWarning={isAiContentGenerationEnabled || hasLocationServices}
            optional
          >
            {redisError && renderError({
              connection: { provider: 'Redis', error: redisError},
            })} <UiText text="Configure an Upstash Redis database directly to enable rate limiting on external services" /> </ChecklistRow>
          <ChecklistRow
            title={hasOpenaiSecretKey && isAnalyzingConfiguration
              ? 'Testing OpenAI connection'
              : 'AI (OpenAI-compatible)'}
            status={hasOpenaiSecretKey}
            isPending={hasOpenaiSecretKey && isAnalyzingConfiguration}
            optional
          >
            {aiError
              && aiContentGenerationProvider === 'openai'
              && renderError({
                connection: { provider: 'OpenAI', error: aiError},
              })} <UiText text="Connect directly to your chosen AI provider. Optionally override the model" /> {' '}
            {'(set OPENAI_MODEL to \'compatible\' to use gpt-4o)'}
            {' '} <UiText text="or base URL for OpenAI-compatible providers." /> {renderEnvVars([
              { variable: 'OPENAI_SECRET_KEY' },
              { variable: 'OPENAI_MODEL', optional: true, value: openaiModel },
              { variable: 'OPENAI_BASE_URL', optional: true },
            ])}
          </ChecklistRow>
          <ChecklistRow
            title={hasLocationServices && isAnalyzingConfiguration
              ? 'Testing Google Places/Geocoding connection'
              : 'Google Places/Geocoding'}
            status={hasLocationServices}
            isPending={hasLocationServices && isAnalyzingConfiguration}
            optional
          >
            {locationError && renderError({
              connection: {
                provider: 'Google Places/Geocoding',
                error: locationError,
              },
            })} <UiText text="Store Google Places/Geocoding API key to add location meta to entities like photos and albums" /> {renderEnvVars(['GOOGLE_PLACES_GEOCODING_API_KEY'])}
          </ChecklistRow>
        </>;
      case 'Location':
        return <>
          <ChecklistRow
            title={uiText('Geo privacy')}
            status={isGeoPrivacyEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to disable collection/display of location-based data" /> {renderEnvVars(['NEXT_PUBLIC_GEO_PRIVACY'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Auto-generate locations')}
            status={autoGenerateLocations && !isGeoPrivacyEnabled}
            showWarning={autoGenerateLocations && isGeoPrivacyEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to disable auto-generation of location data (places/geocoding API key must be configured and geo privacy must be disabled for locations to be auto-generated)" /> {renderEnvVars(['DISABLE_AUTO_GENERATE_LOCATIONS'])}
          </ChecklistRow>
        </>;
      case 'AI Text':
        return <>
          <ChecklistRow
            title={'Auto-generated text fields'}
            status={
              hasAiTextAutoGeneratedFields &&
              isAiContentGenerationEnabled}
            showWarning={hasAiTextAutoGeneratedFields
              && !isAiContentGenerationEnabled}
            optional
          >
            <div>
              {hasAiTextAutoGeneratedFields &&
              AI_AUTO_GENERATED_FIELDS_ALL.map(field =>
                <Fragment key={field}>
                  {renderSubStatus(
                    aiTextAutoGeneratedFields.includes(field)
                      ? 'checked'
                      : 'optional',
                    field,
                  )}
                </Fragment>)}
            </div>
            {!isAiContentGenerationEnabled && <> <UiText text="No provider configured above — these fields will not be generated until one is set up." /> {' '}
            </>} <UiText text="Comma-separated fields to auto-generate when uploading photos. Accepted values: title, caption, tags, description, all, or none" /> {' '} <UiText text="(default:" /> {renderCommaSeparatedList(
              AI_AUTO_GENERATED_FIELDS_DEFAULT,
            )})
            {renderEnvVars(['AI_TEXT_AUTO_GENERATED_FIELDS'])}
          </ChecklistRow>
        </>;
      case 'Performance':
        return <>
          <ChecklistRow
            title={uiText('Static optimization')}
            status={isStaticallyOptimized}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to make site more responsive by enabling static optimization (i.e., rendering pages and images at build time)" /> <div>
              {renderSubStatusWithEnvVar(
                arePhotosStaticallyOptimized ? 'checked' : 'optional',
                'NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTOS',
              )}
              {renderSubStatusWithEnvVar(
                arePhotoOGImagesStaticallyOptimized ? 'checked' : 'optional',
                'NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTO_OG_IMAGES',
              )}
              {renderSubStatusWithEnvVar(
                arePhotoCategoriesStaticallyOptimized ? 'checked' : 'optional',
                'NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTO_CATEGORIES',
              )}
              {renderSubStatusWithEnvVar(
              // eslint-disable-next-line max-len
                arePhotoCategoryOgImagesStaticallyOptimized ? 'checked' : 'optional',
                'NEXT_PUBLIC_STATICALLY_OPTIMIZE_PHOTO_CATEGORY_OG_IMAGES',
              )}
            </div>
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Preserve original uploads')}
            status={areOriginalUploadsPreserved}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to prevent image uploads being compressed before storing" /> {renderEnvVars(['NEXT_PUBLIC_PRESERVE_ORIGINAL_UPLOADS'])}
          </ChecklistRow>
          <ChecklistRow
            title={`Image quality: ${imageQuality}`}
            status={hasImageQuality}
            optional
          > <UiText text="Set environment variable from" /> {'"1-100"'}
            {' '} <UiText text="to control the quality of large photos (" /> {'"100"'} <UiText text="represents highest quality/largest size)" /> {renderEnvVars(['NEXT_PUBLIC_IMAGE_QUALITY'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Image blur')}
            status={isBlurEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to prevent image blur data being stored and displayed" /> {renderEnvVars(['NEXT_PUBLIC_DISABLE_BLUR'])}
          </ChecklistRow>
        </>;
      case 'Categories':
        return <>
          <ChecklistRow
            title={uiText('Visibility and ordering')}
            status={hasCategoryVisibility}
            optional
          >
            {renderOrderedKeyList(categoryVisibility, CATEGORY_KEYS)}
            <div> <UiText text="Configure order and visibility of categories (seen in grid sidebar and CMD-K results) by storing comma-separated values (default:" /> {renderCommaSeparatedList(DEFAULT_CATEGORY_KEYS)})
            </div>
            {renderEnvVars(['NEXT_PUBLIC_CATEGORY_VISIBILITY'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Show on mobile')}
            status={showCategoriesOnMobile}
            optional
          >
            <div className="flex flex-col gap-2">
              <div> <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to prevent categories displaying on mobile grid view" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_CATEGORIES_ON_MOBILE'])}
              </div>
            </div>
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Show image hovers')}
            status={showCategoryImageHover}
            optional
          >
            <div className="flex flex-col gap-2">
              <div> <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to prevent images displaying when hovering over category links" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_CATEGORY_IMAGE_HOVERS'])}
              </div>
            </div>
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Collapsible sidebar')}
            status={collapseSidebarCategories}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to always show expanded category content" /> {renderEnvVars(['NEXT_PUBLIC_EXHAUSTIVE_SIDEBAR_CATEGORIES'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Hide tags with only 1 photo')}
            status={hideTagsWithOnePhoto}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to only show tags with 2 or more photos" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_TAGS_WITH_ONE_PHOTO'])}
          </ChecklistRow>
        </>;
      case 'Sorting':
        return <>
          <ChecklistRow
            title={uiText('Default order')}
            status={hasDefaultSortBy}
            optional
          >
            <div>
              {DEFAULT_SORT_BY_OPTIONS
                .map(({sortBy, configKey }) =>
                  <Fragment key={ sortBy }>
                    {renderSubStatus(
                      sortBy === defaultSortBy ? 'checked' : 'optional',
                      `${configKey}${sortBy === APP_DEFAULT_SORT_BY
                        ? ' (default)'
                        : ''}`,
                    )}
                  </Fragment>)}
            </div> <UiText text="Change default sort on grid/full homepages" /> {renderEnvVars(['NEXT_PUBLIC_DEFAULT_SORT'])}
          </ChecklistRow>
          <ChecklistRow
            title={`Nav sort control: ${navSortControl}`}
            status={hasNavSortControl}
            optional
          > <UiText text="Set environment variable to" /> {'"none"'}, {'"toggle"'} <UiText text="(default), or" /> {'"menu"'} <UiText text=", to control sort UI on grid/full homepages" /> {renderEnvVars(['NEXT_PUBLIC_NAV_SORT_CONTROL'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Color sort')}
            status={isColorSortEnabled}
            experimental
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to enable color-based sorting (forces nav sort control to" /> {'"menu,"'} <UiText text="flags photos missing color data in admin dashboard)—color identification benefits greatly from AI being enabled" /> {renderEnvVars([
              'NEXT_PUBLIC_COLOR_SORT',
            ])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Color sort configuration')}
            status={hasColorSortConfiguration}
            experimental
            optional
          > <UiText text="Configure which colors start first (accepts a hue of 0 to 360, default: 80) and which are considered sufficiently vibrant (accepts a chroma of 0 to 0.37, default: 0.05)" /> <div>
              <EnvVar
                variable="NEXT_PUBLIC_COLOR_SORT_STARTING_HUE"
                value={colorSortStartingHue}
                accessory={renderColorDot({
                  l: 0.85,
                  c: 0.15,
                  h: colorSortStartingHue,
                }, false)}
              />
              <EnvVar
                variable="NEXT_PUBLIC_COLOR_SORT_CHROMA_CUTOFF"
                value={colorSortChromaCutoff}
              />
            </div>
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Priority-based')}
            status={isSortWithPriority}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to take priority field into account when sorting photos (enabling may have performance consequences)" /> {renderEnvVars(['NEXT_PUBLIC_PRIORITY_BASED_SORTING'])}
          </ChecklistRow>
        </>;
      case 'Display':
        return <>
          <ChecklistRow
            title={uiText('Show keyboard shortcut tooltips')}
            status={showKeyboardShortcutTooltips}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to hide keyboard shortcut tooltips in areas like the main nav, and previous/next photo links" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_KEYBOARD_SHORTCUT_TOOLTIPS'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Show EXIF data')}
            status={showExifInfo}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to hide EXIF data" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_EXIF_DATA'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Always show exposure compensation')}
            status={alwaysShowExposureComp}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to always show exposure compensation even when" /> {'it\'s'} <UiText text="0ev" /> {renderEnvVars(['NEXT_PUBLIC_ALWAYS_SHOW_EXPOSURE_COMP'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Show zoom controls')}
            status={showZoomControls}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to hide fullscreen photo zoom controls" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_ZOOM_CONTROLS'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Show taken at time')}
            status={showTakenAtTimeHidden}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to hide taken at time from photo meta" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_TAKEN_AT_TIME'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Show template attribution')}
            status={showRepoLink}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to hide" /> {'\"made with exif-photo-blog\"'} <UiText text="references" /> {renderEnvVars(['NEXT_PUBLIC_HIDE_TEMPLATE_ATTRIBUTION'])}
          </ChecklistRow>
        </>;
      case 'Grid':
        return <>
          <ChecklistRow
            title={uiText('Grid homepage')}
            status={isGridHomepageEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to show grid layout on homepage" /> {renderEnvVars(['NEXT_PUBLIC_GRID_HOMEPAGE'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Masonry grid')}
            status={isMasonryGridEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to show masonry grid layout" /> {renderEnvVars(['NEXT_PUBLIC_MASONRY_GRID'])}
          </ChecklistRow>
          <ChecklistRow
            title={`Grid aspect ratio: ${gridAspectRatio}`}
            status={hasGridAspectRatio}
            optional
          > <UiText text="Set environment variable to any number to enforce aspect ratio" /> {' '} <UiText text="(default is" /> {'"1"'} <UiText text=", i.e., square)—set to" /> {'"0"'} <UiText text="to disable" /> {renderEnvVars(['NEXT_PUBLIC_GRID_ASPECT_RATIO'])}
          </ChecklistRow>
          <ChecklistRow
            title={`Grid density: ${hasHighGridDensity ? 'high' : 'low'}`}
            status={hasGridDensityPreference}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to ensure large thumbnails on photo grid views (if not configured, density is based on aspect ratio)" /> {renderEnvVars(['NEXT_PUBLIC_SHOW_LARGE_THUMBNAILS'])}
          </ChecklistRow>
        </>;
      case 'Design':
        return <>
          <ChecklistRow
            title={`Default theme: ${defaultTheme}`}
            status={hasDefaultTheme}
            optional
          >
            {'Set environment variable to \'light\' or \'dark\''}
            {' '} <UiText text="to configure initial theme" /> {' '} <UiText text="(defaults to" /> {'\'system\''})
            {renderEnvVars(['NEXT_PUBLIC_DEFAULT_THEME'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Uppercase titles')}
            status={arePhotoTitlesUppercase}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to prevent photo titles and captions from displaying in uppercase" /> {renderEnvVars(['NEXT_PUBLIC_DISABLE_UPPERCASE_TITLES'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Photo matting')}
            status={arePhotosMatted}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to constrain the size" /> {' '} <UiText text="of each photo, and display a surrounding border" /> <div className="pt-1 flex flex-col gap-1">
              <EnvVar variable="NEXT_PUBLIC_MATTE_PHOTOS" />
            </div>
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Custom photo matting colors')}
            status={arePhotoMatteColorsConfigured}
            optional
          > <UiText text="Set environment variable hex values (e.g., #cccccc) to override matte colors" /> <div className="pt-1 flex flex-col gap-1">
              <EnvVar
                variable="NEXT_PUBLIC_MATTE_COLOR"
                accessory={matteColor && renderColorDot(matteColor)}
              />
              <EnvVar
                variable="NEXT_PUBLIC_MATTE_COLOR_DARK"
                accessory={matteColorDark && renderColorDot(matteColorDark)}
              />
            </div>
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Tinted folders')}
            status={areFoldersTinted}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to show tinted folders" /> {' '} <UiText text="on" /> {renderLink(PATH_LIBRARY)} <UiText text="page" /> {renderEnvVars(['NEXT_PUBLIC_TINT_FOLDERS'])}
          </ChecklistRow>
        </>;
      case 'Settings':
        return <>
          <ChecklistRow
            title={uiText('Public downloads')}
            status={arePublicDownloadsEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to enable public photo downloads for all visitors" /> {renderEnvVars(['NEXT_PUBLIC_ALLOW_PUBLIC_DOWNLOADS'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Share modal options')}
            status={hasSocialKeys}
            optional
          >
            {renderOrderedKeyList(socialKeys, SOCIAL_KEYS)}
            <div> <UiText text="Configure order and visibility of share modal options by storing comma-separated values (accepts" /> {'"all"'} <UiText text="or" /> {'"none"'} <UiText text=", defaults to" /> {renderCommaSeparatedList(DEFAULT_SOCIAL_KEYS)})
            </div>
            {renderEnvVars(['NEXT_PUBLIC_SOCIAL_NETWORKS'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Site feeds (JSON/RSS)')}
            status={areSiteFeedsEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to enable" /> {' '}
            {renderLink(PATH_FEED_JSON)} <UiText text="and" /> {renderLink(PATH_RSS_XML)}
            {' '} <UiText text="feeds" /> {renderEnvVars(['NEXT_PUBLIC_SITE_FEEDS'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Legacy OG text alignment')}
            status={isOgTextBottomAligned}
            optional
          > <UiText text="Set environment variable to" /> {'"BOTTOM"'} <UiText text="to keep OG image text bottom aligned (default is" /> {'"top"'})
            {renderEnvVars(['NEXT_PUBLIC_OG_TEXT_ALIGNMENT'])}
          </ChecklistRow>
        </>;
      case 'Scripts & Analytics':
        return <>
          <ChecklistRow
            title={uiText('Custom page scripts')}
            status={hasPageScriptUrls}
            optional
          >
            {pageScriptUrls.length > 0 &&
              <div className="mt-2 text-xs space-y-1.5">
                {pageScriptUrls.map(url =>
                  <MaskedScroll
                    key={url}
                    className={clsx(
                      'inline-flex items-center gap-1',
                      'bg-dim rounded-md px-1.5 py-0.5',
                    )}
                    direction="horizontal"
                  >
                    <IoLink size={14} className="shrink-0 translate-y-[0.5px]"/>
                    <span className="font-medium text-nowrap">
                      {url}
                    </span>
                  </MaskedScroll>)}
              </div>} <UiText text="Set environment variable to comma-separated list of URLs to be added to the bottom of the body tag via" /> {'"next/script"'}
            {renderEnvVars(['PAGE_SCRIPT_URLS'])}
          </ChecklistRow>
        </>;
      case 'Debugging':
        return <>
          <ChecklistRow
            title={uiText('Debug outputs')}
            status={isDebuggingEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to disable build identifier and admin configuration export" /> {renderEnvVars(['DISABLE_DEBUG_OUTPUTS'])}
          </ChecklistRow>
        </>;
      case 'Internal':
        return <>
          <ChecklistRow
            title={uiText('Debug tools')}
            status={areAdminDebugToolsEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to temporarily enable features like photo matting, baseline grid, etc." /> {renderEnvVars(['ADMIN_DEBUG_TOOLS'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('SQL debugging')}
            status={isAdminSqlDebugEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to enable console output for all sql queries" /> {renderEnvVars(['ADMIN_SQL_DEBUG'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('Storage debugging')}
            status={isAdminStorageDebugEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to enable storage debugging" /> {renderEnvVars(['ADMIN_STORAGE_DEBUG'])}
          </ChecklistRow>
          <ChecklistRow
            title={uiText('AI model debugging')}
            status={isAdminAiModelDebugEnabled}
            optional
          > <UiText text="Set environment variable to" /> {'"1"'} <UiText text="to enable the" /> <AdminLink href={PATH_ADMIN_AI_MODELS}> <UiText text="AI model comparison" /> </AdminLink> <UiText text="page" /> {renderEnvVars(['ADMIN_AI_MODEL_DEBUG'])}
          </ChecklistRow>
        </>;
    }
  };

  return (
    <ScoreCardContainer>
      {getAdminConfigSections(areInternalToolsEnabled, simplifiedView)
        .map((section) => (
          <ChecklistGroup
            key={section.title}
            title={section.title}
            titleShort={(section as AdminConfigSection).titleShort}
            icon={section.icon}
            optional={!section.required}
            updateHashOnVisible={hasScrolled && !simplifiedView}
          >
            {renderGroupContent(section.title)}
          </ChecklistGroup>
        ))}
      <div className="pl-11 pr-2 sm:pr-11 mt-4 md:mt-7">
        <div> <UiText text="Changes to environment variables require a new deployment to take effect" /> </div>
      </div>
    </ScoreCardContainer>
  );
}
